// <auto-generated />
using AutoMapper.QueryableExtensions.Issue2643;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AutoMapper.QueryableExtensions.Issue2643.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180523162242_WuitCMDBDb")]
    partial class WuitCMDBDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InventoryServer");
                });

            modelBuilder.Entity("AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServerProductLine", b =>
                {
                    b.Property<int>("InventoryServerId");

                    b.Property<int>("ProductId");

                    b.HasKey("InventoryServerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryProductLine");
                });

            modelBuilder.Entity("AutoMapper.QueryableExtensions.Issue2643.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServerProductLine", b =>
                {
                    b.HasOne("AutoMapper.QueryableExtensions.Issue2643.Entities.InventoryServer", "InventoryServer")
                        .WithMany("InventoryServerProductLines")
                        .HasForeignKey("InventoryServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AutoMapper.QueryableExtensions.Issue2643.Entities.Product", "Product")
                        .WithMany("InventoryServerProductLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
